Vue - Vuex
wolox-training/rt-react pull request #105
Opened 2021-06-29 19:20 UTC by renzowolox

## Summary
* Store added
* Refactor books view

## Screenshots
![image](https://user-images.githubusercontent.com/53195970/123855002-c514e480-d8f5-11eb-9635-ff460296d3c7.png)

## Trello Card
[Vuex](https://trello.com/c/lNptlYLN/19-vuex)

2021-06-29 20:42 UTC, rsuescun requested changes

2021-06-29 20:42 UTC, rsuescun commented on vue-training/src/store/index.js
>  export default new Vuex.Store({
Add module for books state

```
/store
|--index.js
|--/modules 
```

Check this https://vuex.vuejs.org/guide/modules.html#module-local-state

2021-06-29 20:42 UTC, rsuescun commented on vue-training/src/views/Books.vue
> +  })
When adding the books module, change this

```
  computed: {
    ...mapState({
      books: state => state.module.bookList
    })
  }
```

2021-06-30 19:59 UTC, rsuescun commented on vue-training/src/views/Books.vue
> +  })
I don't see this change

2021-06-30 20:06 UTC, renzowolox commented on vue-training/src/views/Books.vue
> +  })
look at it in this commit
https://github.com/wolox-training/rt-react/pull/105/commits/5614a3dcf48a6319b594bbd982c532719cd87bb9

2021-07-01 15:21 UTC, rsuescun requested changes

2021-07-01 15:21 UTC, rsuescun commented on vue-training/src/views/Books.vue
> +  })
```suggestion
computed: {
  ...mapState({
    books: state => state.books.bookList
  })
}
```

2021-07-01 19:16 UTC, rsuescun requested changes

2021-07-01 19:16 UTC, rsuescun commented on vue-training/src/views/Books.vue
> +    this.$store.dispatch('books/getBooksList')
Use mapActions

```
  methods: {
    ...mapActions({
      nameAction: 'module/nameAction'
    })
  }
```

See https://vuex.vuejs.org/guide/actions.html#dispatching-actions-in-components

2021-07-01 19:53 UTC, rsuescun approved these changes

2021-07-02 16:21 UTC, merged