tic-tac-toe play diployed
wolox-training/rt-react pull request #24
Opened 2019-12-27 21:50 UTC by renzowolox

## Summary
Tic-tac-toe play developed

## Screenshots
![image](https://user-images.githubusercontent.com/53195970/71533735-50fd1900-28d9-11ea-896c-407c9931388a.png)

## Trello Card
https://trello.com/c/WyRcRY8a

2019-12-30 13:36 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Game/components/Board/index.js
> +        onClick={() => this.props.onClick(i)}
Something we do a lot of times is to destructurate the props when you have to use two or more :point_down: 
```
const { squares, onClick } = this.props;
...
value={squares[i]} 
onClick={() => onClick(i)}
```

2019-12-30 13:40 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Game/components/Board/index.js
> +        onClick={() => this.props.onClick(i)}
Another point is that we dont use inline functions in props `onClick={() => this.props.onClick(i)}` because of performance. You can do something like this :point_down: 
```
<Square 
        value={squares[i]} 
        onClick={onClick}
        id={i}
>
```
And then in the Square component you can declare a function using both props
```
const onHandleClick = () => {
      const { id, onClick } = this.props;
      onClick(id);
}
```
And `onHandleClick` goes where you use onClick in the Square component

2019-12-30 13:41 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Game/components/Square/index.js
> +
Add empty line

2019-12-30 13:41 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Game/components/Square/index.js
> +      onClick={() => props.onClick()}
Here you can call the `onHandleClick` which I explained before

2019-12-30 13:43 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Game/components/Square/index.js
> +    <button type="button"
Check if `eslint` say something for this
```
<button
     type="button" 
     className={styles.square} 
....
```

2019-12-30 13:46 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +function calculateWinner(squares) {
This function you can move to a different file, for example, yo can create a `utils` file in the same folder and import it from there to here

2019-12-30 13:50 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +    const history = this.state.history.slice(0, this.state.stepNumber + 1);
Here you can also destructure the state
`const { history, xIsNext, stepNumber } this.state;`

2019-12-30 13:55 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +    }
You can extract this code to a function `getStatus`

2019-12-30 13:56 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +        'Go to game start';
If you want to can do like this :point_right: `const desc = `Go to ${move ? `move #${move}` : 'game start'}`;` but its not necessary :smile:

2019-12-30 13:57 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +            onClick={(i) => this.handleClick(i)}
Check this `onClick={this.handleClick}`

2019-12-30 13:58 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +      history: history.concat([{
Try if you can change the `concat` function with a spread syntax :wink:

2019-12-30 16:35 UTC, renzowolox commented on react/tic-tac-toe/src/app/screens/Game/components/Board/index.js
> +        onClick={() => this.props.onClick(i)}
:+1:

2019-12-30 16:37 UTC, renzowolox commented on react/tic-tac-toe/src/app/screens/Game/components/Board/index.js
> +        onClick={() => this.props.onClick(i)}
:+1:

2019-12-30 16:38 UTC, renzowolox commented on react/tic-tac-toe/src/app/screens/Game/components/Square/index.js
> +      onClick={() => props.onClick()}
:+1:

2019-12-30 16:42 UTC, renzowolox commented on react/tic-tac-toe/src/app/screens/Game/components/Square/index.js
> +    <button type="button"
:+1:

2019-12-30 17:08 UTC, renzowolox commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +function calculateWinner(squares) {
:+1:

2019-12-30 18:05 UTC, renzowolox commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +    }
:+1:

2019-12-30 18:06 UTC, renzowolox commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +        'Go to game start';
:+1:

2019-12-30 18:07 UTC, renzowolox commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +            onClick={(i) => this.handleClick(i)}
:+1:

2020-01-02 13:11 UTC, erikankodelia requested changes

2020-01-02 13:11 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/components/Square/index.js
> +const Square = (props) => {
When create a new component,  we use function instead of const. So you can change it to something like this:

```function Square({ id, onClick, value }) {  ... }```

2020-01-02 13:11 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +            onClick={ (i) => this.handleClick(i) }
It is not necessary to create an arrow function here. You can write directly this.handleClick

2020-01-02 19:54 UTC, erikankodelia approved these changes

2020-01-02 21:11 UTC, ghost approved these changes

2020-01-02 21:51 UTC, merged