Redux I - actions, reducers, store.
wolox-training/rt-react pull request #29
Opened 2020-01-02 17:59 UTC by renzowolox

## Summary
* Books listed
* Books searcher

## Screenshots
![react-books](https://user-images.githubusercontent.com/53195970/71683089-4ecf0a80-2d70-11ea-8a99-7a18bffe3c20.gif)

## Trello Card
https://trello.com/c/cnSH3vfa

2020-01-02 18:18 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/index.js
> +      books: this.props.getBooks()
You can do this componentDidMount() => this.props.getBooks();
after that you have the `books` like a prop, so you can use directly `this.props.books` and it is not necessary to add it to the class state.

2020-01-02 18:18 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/index.js
> +            this.props.books.map(this.renderBooks)
You can destructurate in `const { onSearch, books } = this.props; `

2020-01-02 18:20 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/index.js
> +          {this.props.books.length ? (
Do you test if length is 0? Try it :wink:

2020-01-02 18:20 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/index.js
> +        {this.props.bookSelected.length ? (
Same as before with length 0

2020-01-02 18:21 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/index.js
> +import actionsCreators from '@redux/book/actions';
Its okey but I prefer if you can give it another name like `booksActions`

2020-01-02 18:23 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/index.js
> +import { Provider } from 'react-redux';
This import has to be avobe :point_down: 
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from '@screens/App';
import { Provider } from 'react-redux';
```
Another tip if eslint gives you an error, we try to solve it without comments :wink:

2020-01-02 18:29 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/redux/book/reducer.js
> +      state.books = state.originalData;
Is it necessary?

2020-01-02 18:29 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/redux/book/reducer.js
> +      state.originalData = action.payload;
s it necessary?

2020-01-02 18:33 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/redux/book/reducer.js
> +        books: state.books.filter(book => book.name.toLowerCase().search(action.payload) !== -1)
You can create a utils file and add this filter to a function.. so you can have this here :point_down: 
`return { ...state, books: filteredBooks(state.books, action.payload.search) };`
You can do this to every future actions

Also is better if you can change this in actions
```
searchBook: value => ({
    type: actions.SEARCH_ITEM,
    payload: { search: value }
  })
```
And then call it like  action.payload.search. This its good if you have to pass 2 parameters

2020-01-02 19:38 UTC, renzowolox commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/index.js
> +          {this.props.books.length ? (
Yes, if length is 0, the result is this.
![react-test-length](https://user-images.githubusercontent.com/53195970/71688255-3fef5480-2d7e-11ea-9d9b-7386af1f3e28.gif)

2020-01-02 19:50 UTC, renzowolox commented on react/finger-exercises/redux/02 - react-redux/src/redux/book/reducer.js
> +      state.books = state.originalData;
Without this statement, the state is modified and when i remove the filter, books that appear aren't all of them.
![test-original-data](https://user-images.githubusercontent.com/53195970/71689081-ebe56f80-2d7f-11ea-9581-4bbcdf47c830.gif)

2020-01-02 19:52 UTC, renzowolox commented on react/finger-exercises/redux/02 - react-redux/src/redux/book/reducer.js
> +      state.originalData = action.payload;
I did this to save the original state.

2020-01-02 21:12 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/index.js
> +  // eslint-disable-next-line react/prop-types
You have to add Proptypes for this `getBooks: func` so you can avoid this comment

2020-01-02 21:13 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/index.js
> +    const { bookSelected } = this.props;
If its one prop, you can use directly `this.props.bookSelected`

2020-01-02 21:18 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/index.js
> +        {bookSelected.length ? (
Try `{bookSelected.length > 0 && (...)}` so you can avoid the `null`

2020-01-03 13:51 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/redux/book/reducer.js
> +        bookSelected: state.bookSelected.filter(book => book.id !== action.payload.bookId)
You can create a function in utils for this remove as you did in `filteredBooks`

2020-01-03 16:35 UTC, erikankodelia requested changes

2020-01-03 16:35 UTC, erikankodelia commented on react/finger-exercises/redux/02 - react-redux/src/redux/book/actions.js
> +    payload: { book: item }
If you change the name of the param then here you can write ```payload: { book }``` directly

2020-01-03 16:35 UTC, erikankodelia commented on react/finger-exercises/redux/02 - react-redux/src/redux/book/reducer.js
> +      state.originalData = action.payload;
I think that you can save it equal that you save `books`.

```return { ...state, originalData: action.payload, books: action.payload }```

2020-01-03 20:36 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/components/ShoppingCart/index.js
> +        <Button className={styles.buttonCart} onClick={this.props.toggleContent}>
Destructure `props`

2020-01-03 20:38 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/index.js
> +          <ShoppingCart data={bookSelected} addItem={this.addItem} removeItem={this.props.removeItem} />
You can add the `removeItem` to `const { onSearch, books, bookSelected } = this.props;`

2020-01-03 20:39 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/redux/book/reducer.js
> +      state.books = state.originalData;
You can do the same as `GET_BOOKS` returns

2020-01-06 11:36 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/components/ShoppingCart/index.js
> +        <div className={`${styles.container} ${open ? styles.open : ''}`}>
A useful tip for this is the library [classnames](https://www.npmjs.com/package/classnames)
Its a good way to avoid empty classnames, for example in this case is it is not open, you will have `class="container "`. And in other cases it will be `class=" "`.

If you want you can implement this but it is not necessary :wink:

2020-01-06 11:38 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/redux/book/reducer.js
> +        bookSelected: state.bookSelected.map(book => {
Move this to a util function like `addToCart`, `removeFromCart` and `filteredBooks`

2020-01-06 14:48 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/components/ShoppingCart/index.js
> +const classNames = require('classnames');
`import classNames from 'classnames'`

2020-01-06 14:52 UTC, fededirocco34 commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/components/ShoppingCart/index.js
> +    getTotalCart(data);
Instead of calling this method here you can use `componentDidMount()` lifecycle method

2020-01-06 16:21 UTC, ghost submitted a review, later dismissed

2020-01-06 19:33 UTC, erikankodelia commented on react/finger-exercises/redux/02 - react-redux/src/app/screens/App/components/ShoppingCart/index.js
> +  componentDidUpdate = () => this.props.getTotalCart(this.props.data);
Change to `componentDidUpdate() {...}` because it is a method class

2020-01-06 19:33 UTC, erikankodelia commented on react/finger-exercises/redux/02 - react-redux/src/redux/book/utils.js
> +  books = originalData;
It is not necessary

2020-01-06 20:46 UTC, erikankodelia approved these changes

2020-01-07 13:00 UTC, ghost approved these changes

2020-01-07 15:49 UTC, merged