Login form added
wolox-training/rt-react pull request #31
Opened 2020-01-08 23:24 UTC by renzowolox

## Summary
* Login form added with redux-form

## Screenshots
![login-form](https://user-images.githubusercontent.com/53195970/72024707-c8756580-3254-11ea-9ede-d6d95bdd9d86.gif)

## Trello Card
* https://trello.com/c/WaAL48gT

2020-01-09 11:55 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Login/components/renderInput.js
> +const renderField = ({ input, label, type, className, meta: { touched, error, warning }}) => (
I will include this file into a component in `app/components/InputLabel` and defined it like a function. If you see you can think it like a component for input forms.

2020-01-09 11:58 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Login/components/validate.js
> +	minValue8: minValue(8)
Its a good approach to use numbers into contants :point_down: 
`minPasswordValue: minValue(MIN_PASSWORD_VALUE)`

2020-01-09 11:58 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Login/index.js
> +let LoginForm = props => {
Define it like a `function`

2020-01-09 12:03 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Login/styles.module.scss
> +  color: #F00;
In projects we add every color in one file inside `src/scss/colors.scss`
We define like `$white: #FFF;` and then we import this file here and call it `$white`

2020-01-09 12:03 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Login/styles.module.scss
> +  background-color: #0000FF;
Same as before

2020-01-09 12:03 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Login/styles.module.scss
> +  color: #FFF;
Same as before

2020-01-09 12:09 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/index.js
> +  return <Login />;
Here you have to use `Router` for checking routes and also implement some component for checking if the user is logged. In this case you are only returning the Login but not the Game. Did you see it from the training?

2020-01-09 16:18 UTC, erikankodelia requested changes

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/components/inputLabel.js
> +	return (
Fix the indentation

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/components/loginForm.js
> +      <form onSubmit={handleSubmit}>
Move the className in the div to the form

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/components/validate.js
> +	value && value.length < min ? `Most be at least ${min}` : undefined;
Fix indentation here too

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/components/validate.js
> +	required: value => value ? undefined : 'Required field',
Same here

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/index.js
> +  submit = values => {
You can destructuring here like: `submit = ({ email, password }) => { ... }`

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/index.js
> +const mapStateToProps = state => ({});
Remove it

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/index.js
> +export default connect(mapStateToProps, mapDispatchToProps)(Login);
And change mapStateToProps to null

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/index.js
> +  submit = values => {
Or you can change the definition of loginUser to:

`loginUser: ({ email, password }) => dispatch(actionCreators.loginUser(email, password))`

And you don't need to create submit function and directly write:

`<LoginForm onSubmit={this.props.loginUser} />`

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/styles.module.scss
> +  width: 300px;
Try to not set width like this. Change to max-width: 300px and width: 100%

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/styles.module.scss
> +  margin-top: 5px;
We try to use margin-bottom instead of margin-top. So remove margin here and add margin-bottom in the password field

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/redux/login/actions.js
> +	loginUser: (email, password) => async dispatch => {
Fix indentation

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/redux/login/reducer.js
> +function reducer(state = initialState, action){
Same here

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/redux/login/reducer.js
> +function reducer(state = initialState, action){
This reducer doesn't do anything

2020-01-09 16:18 UTC, erikankodelia commented on react/tic-tac-toe/src/services/LoginService.js
> +	login: (email, password) => api.post('/login', {
Fix indentation

2020-01-10 14:40 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/index.js
> +      <Redirect to="/login" />
What happens if you enter `/` or `/incorrectpage` and the user is logged? Maybe you can show a 404 page not found and not redirect to the login

2020-01-10 14:41 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +    // const gamesHistory = this.props.games.map(game => {
Why is it commented this code?

2020-01-10 14:41 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Login/components/authorizedRoute.js
> +    console.log('Authorized routes');
Remove this

2020-01-10 14:45 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Login/components/loginForm.js
> +          type="text"
You can define some constants for this props in a `constants.js` like :point_down: 
```
LOGIN_FIELDS = {
    name: 'name',
    password: 'password'
}
```

And the same por field types and labels.

2020-01-10 14:46 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Login/components/validate.js
> +    minValue8: minValue(MIN_PASSWORD_LENGTH)
I would change the name to `minValuePassword`

2020-01-10 14:48 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Login/index.js
> +    if (tokenGame) this.props.setTokenFromLocalStorage(tokenGame);
I would move this logic to the `AuthorizedRoute` component.

2020-01-10 14:48 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Login/index.js
> +  submit = ({ email, password}) => {
`password })`

2020-01-10 14:50 UTC, fededirocco34 commented on react/tic-tac-toe/src/constants/validateData.js
> +export const MIN_PASSWORD_LENGTH = 8;
Add empty line

2020-01-10 14:50 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Login/index.js
> +    const tokenGame = localStorage.getItem('tokenGame');
You can define a constant for `tokenGame`

2020-01-10 14:51 UTC, fededirocco34 commented on react/tic-tac-toe/src/redux/login/actions.js
> +      localStorage.setItem('tokenGame', response.data.token);
Same as before

2020-01-10 14:51 UTC, fededirocco34 commented on react/tic-tac-toe/src/redux/login/actions.js
> +			console.log(response.data);
Remove this

2020-01-10 14:52 UTC, fededirocco34 commented on react/tic-tac-toe/src/redux/login/actions.js
> +    dispatch(push('game'));
/game?

2020-01-10 14:53 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/index.js
> +      <Route path="/login" component={Login} />
You can define a `routes.js` with every route constant in the app (replace both in every place)

2020-01-10 17:35 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/NotFound/index.js
> +
Add empty line

2020-01-10 17:35 UTC, fededirocco34 commented on react/tic-tac-toe/src/constants/tokenGame.js
> +export const TOKEN_GAME = 'tokenGame';
You can define this file as auth.js

2020-01-10 17:38 UTC, fededirocco34 commented on react/tic-tac-toe/src/constants/validateData.js
> +export const MIN_PASSWORD_LENGTH = 8;
I prefer to move this file into `Login` component as `constants.js`

2020-01-13 11:45 UTC, fededirocco34 commented on react/tic-tac-toe/src/redux/login/actions.js
> +			dispatch(push('/game'));
As same as the other PR, import the `ROUTES` constants and replace this string

2020-01-13 11:45 UTC, fededirocco34 commented on react/tic-tac-toe/src/redux/login/actions.js
> +		dispatch(push('/game'));
Same as before

2020-01-13 12:25 UTC, erikankodelia submitted a review, later dismissed

2020-01-13 12:38 UTC, ghost approved these changes

2020-01-13 12:46 UTC, erikankodelia approved these changes

2020-01-13 12:47 UTC, merged