Routing II - Topbar
wolox-training/rt-react pull request #32
Opened 2020-01-10 21:00 UTC by renzowolox

## Summary
* Topbar added
* Links to Profile and Game views
* Link to Logout

## Screenshots
![game-navbar](https://user-images.githubusercontent.com/53195970/72186010-fa143b00-33d2-11ea-852e-86ae356a0b6d.gif)

## Trello Card
* https://trello.com/c/AicOPqeT

2020-01-13 11:34 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Login/components/authorizedRoute.js
> +            <div>
When you need a empty div you can use `Fragment`
`import React, { Fragment } from 'react'`
`<Fragment></Fragment>`

2020-01-13 11:35 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Navbar/styles.module.scss
> +}
Add empty line

2020-01-13 11:36 UTC, fededirocco34 commented on react/tic-tac-toe/src/redux/login/actions.js
> +		dispatch(push('/login'));
You can import the `ROUTES` constants. Replace them in every `push`.

2020-01-13 11:37 UTC, fededirocco34 commented on react/tic-tac-toe/src/redux/login/reducer.js
> +			return {
Fix indentation (if you can :laughing: )

2020-01-13 11:37 UTC, fededirocco34 commented on react/tic-tac-toe/src/redux/login/reducer.js
> +			};
Fix indentation (if you can :laughing: )

2020-01-13 11:38 UTC, fededirocco34 commented on react/tic-tac-toe/src/redux/login/reducer.js
> +			return state;
Same as before

2020-01-13 12:50 UTC, erikankodelia requested changes

2020-01-13 12:50 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Navbar/index.js
> +class Navbar extends React.Component {
Import the Component directly like this: `import React, { Component } from react`

2020-01-13 12:50 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Navbar/styles.module.scss
> +  margin-bottom: 20px;
It is not necessary because you set it in the next line

2020-01-13 12:50 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Profile/index.js
> +class Profile extends React.Component {
Same here

2020-01-13 12:50 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Profile/index.js
> +          Back
It is a good practice to extract the constants in this file to another file.

2020-01-13 12:50 UTC, erikankodelia commented on react/tic-tac-toe/src/redux/login/actions.js
> +		dispatch(goBack());
The spaces in this file are not correct

2020-01-13 22:21 UTC, erikankodelia requested changes

2020-01-13 22:21 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Profile/index.js
> +class Profile extends Component {
It is not necessary to create a class here. Change to function.

2020-01-13 22:22 UTC, erikankodelia requested changes

2020-01-13 22:22 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Profile/index.js
> +          {BACK_LABEL}
You can do the same with the other strings in this file

2020-01-13 23:33 UTC, renzowolox commented on react/tic-tac-toe/src/app/screens/Profile/index.js
> +class Profile extends Component {
Shouldn't this be a class to use the props store?

2020-01-14 13:07 UTC, fededirocco34 commented on react/tic-tac-toe/src/app/screens/Profile/index.js
> +class Profile extends Component {
You can also use props declaring functions

2020-01-14 16:25 UTC, erikankodelia submitted a review, later dismissed

2020-01-15 12:59 UTC, ghost submitted a review, later dismissed

2020-01-15 16:25 UTC, ghost approved these changes

2020-01-15 16:49 UTC, erikankodelia approved these changes

2020-01-15 16:51 UTC, merged